apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: swiggy-deploy
  name: swiggy-deploy
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 3000
  selector:
    app: swiggy-deploy
  type: NodePort
status:
  loadBalancer: {}